### ISSUE TITLE
[ONBOARDING] AMP

### ISSUE THREAD

**Issue by jorydotcom** [openjs-foundation/project-onboarding#24]
## Project Onboarding Checklist - AMP

**Intended Stage: Growth**

- [ ] Adopt the OpenJS Foundation Code of Conduct _(blocked on openjs-foundation/cross-project-council#271, tracked in https://github.com/ampproject/wg-codeofconduct/issues/6)_
- [ ] Update project CoC reporting methods to include OpenJS Foundation escalation path _(blocked on openjs-foundation/cross-project-council#271, tracked in https://github.com/ampproject/wg-codeofconduct/issues/6)_
- [ ] Transfer official domains to OpenJS Foundation _(tracked in https://github.com/ampproject/wg-foundation-onboarding/issues/3)_
- [ ] Identify and document other core project infrastructure _(tracked in https://github.com/ampproject/wg-infra/issues/18 and https://github.com/ampproject/wg-infra/issues/19)_
- [ ] If choosing to use a Contributor License Agreement (CLA) or Developer Certificate of Origin (DCO), make selection and implement appropriate tool _(blocked on openjs-foundation/cross-project-council#124, tracked in https://github.com/ampproject/meta-tsc/issues/25)_
- [ ] Add or Update Governance.md document (required for Impact stage) _(tracked in https://github.com/ampproject/meta/issues/46)_
- [ ] Confirm required files in place (CODE_OF_CONDUCT.md, LICENSE.md) _(tracked in https://github.com/ampproject/wg-foundation-onboarding/issues/7 and https://github.com/ampproject/wg-codeofconduct/issues/6)_
- [ ] [Project Charter](https://github.com/openjs-foundation/cross-project-council/blob/master/PROJECT_CHARTER_TEMPLATE.md) is published on website or github _(tracked in https://github.com/ampproject/meta/issues/45)_
- [ ] Update legal copyright notice on project website and github _(blocked on openjs-foundation/cross-project-council#124, tracked in https://github.com/ampproject/wg-foundation-onboarding/issues/12)_
- [ ] Add OpenJS Foundation logo to project website _(blocked on openjs-foundation/cross-project-council#280, tracked in https://github.com/ampproject/wg-outreach/issues/60)_
- [x] Add Project logo to OpenJS Foundation website; update PROJECTS.md file
- [ ] Transfer logomark to the OpenJS Foundation _(tracked in https://github.com/ampproject/wg-foundation-onboarding/issues/8)_
- [ ] If project is using crowdfunding platforms, add disclaimer to platforms _(tracked in https://github.com/ampproject/wg-foundation-onboarding/issues/10)_
- [ ] Identify individuals from the project to join the CPC _(tracked in https://github.com/ampproject/wg-foundation-onboarding/issues/11)_
- [ ] Document project and foundation contacts for:
  * marketing & social media
  * infrastructure
  * legal/governance help
  _(tracked in  https://github.com/ampproject/wg-foundation-onboarding/issues/4)_
